language: node_js
sudo: false
node_js:
  - "8.4.0"
  - "8.3.0"
  - "8.2.1"
  - "7.10.1"
  - "7.9.0"
  - "7.8.0"
  - "6.11.2"
  - "6.11.1"
  - "6.11.0"
  - "6.10.3"
install:
  - npm install
script:
  - npm lint