language: node_js
sudo: true
group: edge

node_js:
  - "8.4.0"
  - "8.3.0"
  - 7

cache:
  yarn: true
  directories:
    - node_modules

services:
  - mongod
  - redis-server

install:
  - yarn install
script:
  - npm run lint && npm test
