language: node_js
sudo: false
group: edge

node_js:
  - "8.4.0"
  - "8.3.0"
  - 7

cache:
  yarn: true
  directories:
    - node_modules

addons:
  services:
    - mongod
services:
  - redis-server

before_script:
  # Begin modification of the default mongoDB instance
  - sudo echo "replSet = rs0" | sudo tee -a /etc/mongodb.conf
  - sudo echo "oplogSize = 250" | sudo tee -a /etc/mongodb.conf
  - sudo echo "nojournal = true" | sudo tee -a /etc/mongodb.conf

  # Wipe out the data directory so we are clean with our configuration
  - sudo rm -rf /var/lib/mongodb/*

  # Start up the service using the normal init script
  - sudo cat /etc/mongodb.conf
  - sleep 10
  - sudo service mongodb restart

  # Create the replicaSet and then wait for it to become clean with a primary and secondary
#before_script:
  - mongo --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]})"
#  - sleep 5

install:
  - yarn install
script:
  - npm run lint
